version: '3'
services:

  agh.monitor:
    image: agh/monitor:0.1.0
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}